name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Vercel CLI globally
        run: npm install -g vercel@latest

      - name: Link Vercel Project
        run: vercel link --token ${{ secrets.VERCEL_TOKEN }} --yes --project ${{ secrets.VERCEL_PROJECT_ID }} --scope ${{ secrets.VERCEL_ORG_ID }}

      - name: Deploy to Production
        run: vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

      - name: Get Deployment URL
        id: vercel
        run: |
          DEPLOYMENT_URL=$(vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes --scope ${{ secrets.VERCEL_ORG_ID }} --json | jq -r '.url')
          echo "url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT
          echo "Deployed to: $DEPLOYMENT_URL"

      - name: Show Deployment URL
        run: echo "Deployed to: ${{ steps.vercel.outputs.url }}"
