name: run Tests

on: 
  push:

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - uses:  actions/checkout@v3
    - name: Run Tests
      run: |
        npm install
        npm test

deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
      node-version: 20
    - run: npm install

    - name: Deploy to Vercel
      run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
      env: 
        VERCEL_ORG_ID: ${{ secrets.VERCEL.USER_ID }}
        VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
